name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Download golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.linux-amd64.tar.gz

    - name: Install golang-migrate
      run: |
        sudo mkdir migrate
        tar -xvf migrate.linux-amd64.tar.gz -C ./migrate
        sudo mv migrate /usr/bin
        which migrate
    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test